server:
  port: 8888
spring:
  application:
    name: view-config-server
  #开启基于http basic的认证
  #security:
    #user:
      #name: lihy
      #password: 123456
  cloud:
    config:
      #配置仓库的分支
      label: master
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/huanyingtoyou/view-home-config-2.0
          #配置仓库路径
          search-paths: datasource, view*
          #search-paths: {profile}
          #searchPaths: '{application}'
          #访问git仓库的用户名（如果git仓库为公开仓库，可以不填写用户名和密码）
          username:
          #访问git仓库的用户密码
          password:
eureka:
  client:
    serviceUrl:
      #defaultZone: http://lihy:520@localhost:8088/eureka/
      defaultZone: http://localhost:8088/eureka/